name: goreleaser

on: push
#on:
  #push:
    #tags:
    #  - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: make interface-install-deps
        run: make interface-install-deps
      - name: make client-build
        run: make client-build
      - name: make goreleaser-vue
        run: make goreleaser-vue
      - name: make statik
        run: cd ./mailserver-configurator-interface; ~/go/bin/statik -f -src=./public
      - name: tree
        run: tree
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
